[langserver]
dreamchecker = true

[dmdoc]
use_typepath_names = true

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true

[debugger]
engine = "auxtools"

[diagnostics]
# Raised by DreamChecker
disabled_directive = "error"
sets_directive_twice = "error"
invalid_lint_directive_value = "error"
invalid_set_value = "error"
unknown_linter_setting = "error"
override_missing_keyword_arg = "error"
must_not_override = "error"
must_call_parent = "error"
final_var = "error"
private_proc = "error"
protected_proc = "error"
private_var = "error"
protected_var = "error"
must_be_pure = "error"
must_not_sleep = "error"
redefined_proc = "off"
ambiguous_in_lhs = "error"
ambiguous_not_bitwise = "error"
no_typehint_implicit_new = "error"
field_access_static_type = "error"
proc_call_static_type = "error"
proc_has_no_parent = "error"
no_operator_overload = "error"
unreachable_code = "error"
control_condition_static = "error"
if_condition_determinate = "error"
loop_condition_determinate = "error"

# Raised by Lexer
integer_precision_loss = "error"

# Raised by Parser
duplicate_include = "error"
macro_redefined = "error"
macro_undefined_no_definition = "error"

# Raised by Object Tree
override_precedes_definition = "error"

[map_renderer]
hide_invisible = [
	"/obj/effect/step_trigger",
	"/obj/abstract",
	"/turf/unsimulated/mask",
	"/obj/effect/shuttle_landmark",
	"/obj/effect/overmap",
]

[map_renderer.render_passes]
overlays = false
gravity-gen = false
pretty = false
icon-smoothing = false
icon-smoothing-2016 = true
smart-cables = false
# TODO: add support for directional_offsets var to Jupyterkat's fork?
offsets = false
# maybe also add support for our random spawners?
random = false
spawners = false