name: CI Suite
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BYOND_MAJOR: 512
  BYOND_MINOR: 1485
  SPACEMAN_DMM_VERSION: suite-1.5

jobs:
  DreamChecker:
    runs-on: ubuntu-latest
    name: DreamChecker
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Cache
        uses: actions/cache@v2.1.3
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install DreamChecker
        run: bash scripts/install-spaceman-dmm.sh dreamchecker
      - name: Run DreamChecker
        run: ~/dreamchecker
  Code:
    runs-on: ubuntu-latest
    name: Code Checks
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Cache
        uses: actions/cache@v2.1.3
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Setup Workspace
        run: |
          sudo apt update
          sudo apt install -y uchardet dos2unix
      - name: Run Code Tests
        env:
          TEST: CODE
        run: bash test/run-test.sh
  Maps:
    runs-on: ubuntu-latest
    name: Map Check (${{ matrix.Map }})
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        Map: ["tradeship"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Cache
        uses: actions/cache@v2.1.3
        with:
          path: $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
          key: ${{ runner.os }}-byond-${{ env.BYOND_MAJOR }}-${{ env.BYOND_MINOR }}
      - name: Setup Workspace
        run: sudo apt update
      - name: Run Tests
        env:
          TEST: MAP
          MAP_PATH: ${{ matrix.Map }}
        run: bash test/run-test.sh